### ISSUE TITLE
I wonder if this thing could be turned into a preprocessor for OCaml

### ISSUE THREAD

**Issue by UnixJunkie** [chrisnevers/macro-expander#1]
Because, sometimes, I just want macros in OCaml. :)

**Comment by jeapostrophe** [comment]
There are multiple attempts to do this in OCaml:

https://jaredforsyth.com/posts/template-based-macros-for-reason-ocaml/

https://github.com/ocamllabs/ocaml-macros/

--
Jay McCarthy
Associate Professor @ CS @ UMass Lowell
http://jeapostrophe.github.io
Vincit qui se vincit.

**Comment by UnixJunkie** [comment]
I did not know them, thanks.

**Comment by UnixJunkie** [comment]
I just know cppo, but it is no more maintained.
